name: Package extension

on: [push]

jobs:
    build_vhdl_ls_ubuntu:
        name: Build vhdl_ls - Ubuntu, musl
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Rust HDL
              uses: actions/checkout@v2-beta
              with:
                  repository: kraigher/rust_hdl
            - name: Build vhdl_ls
              run: cargo build --release --package vhdl_ls --target x86_64-unknown-linux-gnu
            - name: Upload vhdl_ls executable
              uses: actions/upload-artifact@v1
              with:
                  name: vhdl_ls-ubuntu
                  path: target/x86_64-unknown-linux-gnu/release
    
    build_vhdl_ls_windows:
        name: Build vhdl_ls - Windows, MSVC
        runs-on: windows-latest
        steps:
            - name: Checkout Rust HDL
              uses: actions/checkout@v2-beta
              with:
                  repository: kraigher/rust_hdl
            - name: Build vhdl_ls
              run: cargo build --release --package vhdl_ls --target x86_64-pc-windows-msvc
            - name: Upload vhdl_ls executable
              uses: actions/upload-artifact@v1
              with:
                  name: vhdl_ls-win
                  path: target/x86_64-pc-windows-msvc/release
    
    package_extension:
        name: Package extension
        needs: [build_vhdl_ls_ubuntu, build_vhdl_ls_windows]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v1
              with:
                  name: vhdl_ls-ubuntu
            - uses: actions/download-artifact@v1
              with:
                  name: vhdl_ls-win
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: '10'
            - run: npm install
            - run: npm package
