name: Package extension

on: [push]

jobs:
    prepare_linux:
        name: Prepare Linux (Ubuntu)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Rust HDL
              uses: actions/checkout@v2-beta
              with:
                  repository: kraigher/rust_hdl
            - name: Build vhdl_ls
              run: cargo build --release --package vhdl_ls --target x86_64-unknown-linux-gnu
            - name: Copy server
              run: mkdir server && cp target/x86_64-unknown-linux-gnu/release/vhdl_ls server
            - name: Upload vhdl_ls executable
              uses: actions/upload-artifact@v1
              with:
                  name: vhdl_ls-ubuntu
                  path: server
    
    prepare_windows:
        name: Prepare Windows
        runs-on: windows-latest
        steps:
            - name: Checkout Rust HDL
              uses: actions/checkout@v2-beta
              with:
                  repository: kraigher/rust_hdl
            - run: cargo build --release --package vhdl_ls --target x86_64-pc-windows-msvc
            - run: mkdir server
            - run: copy target\x86_64-pc-windows-msvc\release\vhdl_ls.exe server
            - uses: actions/upload-artifact@v1
              with:
                  name: vhdl_ls-win
                  path: server
    
    package:
        name: Package
        needs: [prepare_linux, prepare_windows]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v1
              with:
                  name: vhdl_ls-ubuntu
            - uses: actions/download-artifact@v1
              with:
                  name: vhdl_ls-win
            - uses: actions/checkout@v1
            - run: ls
            - uses: actions/setup-node@v1
              with:
                  node-version: '10'
            - run: npm install
            - run: vsce package
