name: Package

on: [push]

jobs:
    prepare_linux:
        if: startsWith(github.ref, 'refs/tags/v')
        name: Prepare Linux (Ubuntu)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Rust HDL
              uses: actions/checkout@v2-beta
              with:
                  repository: kraigher/rust_hdl
            - name: Build vhdl_ls
              run: cargo build --release --package vhdl_ls --target x86_64-unknown-linux-gnu
            - name: Copy server
              run: mkdir server && cp target/x86_64-unknown-linux-gnu/release/vhdl_ls server
            - name: Upload vhdl_ls executable
              uses: actions/upload-artifact@v1
              with:
                  name: vhdl_ls-ubuntu
                  path: server
    
    prepare_windows:
        if: startsWith(github.ref, 'refs/tags/v')
        name: Prepare Windows
        runs-on: windows-latest
        steps:
            - name: Checkout Rust HDL
              uses: actions/checkout@v2-beta
              with:
                  repository: kraigher/rust_hdl
            - run: cargo build --release --package vhdl_ls --target x86_64-pc-windows-msvc
            - run: mkdir server
            - run: copy target\x86_64-pc-windows-msvc\release\vhdl_ls.exe server
            - uses: actions/upload-artifact@v1
              with:
                  name: vhdl_ls-win
                  path: server
    
    package:
        if: startsWith(github.ref, 'refs/tags/v')
        name: Package
        needs: [prepare_linux, prepare_windows]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: mkdir server
            - uses: actions/download-artifact@v1
              with:
                  name: vhdl_ls-ubuntu
                  path: vhdl_ls/vhdl_ls-ubuntu
            - run: cp vhdl_ls/vhdl_ls-ubuntu/vhdl_ls ./server
            - uses: actions/download-artifact@v1
              with:
                  name: vhdl_ls-win
                  path: vhdl_ls/vhdl_ls-win
            - run: cp vhdl_ls/vhdl_ls-win/vhdl_ls.exe ./server
            - run: rm -r vhdl_ls
            - run: ls server
            - uses: actions/setup-node@v1
              with:
                  node-version: '10'
            - run: npm install
            - run: npm install -g vsce
            - run: vsce package
            - run: mkdir vhdl-ls && cp *.vsix vhdl-ls
            - uses: actions/upload-artifact@v1
              with:
                  name: vhdl-ls
                  path: vhdl-ls
         
    publish:
#         if: startsWith(github.ref, 'refs/tags/v')
        name: Publish
        runs-on: ubuntu-latest
        steps:
#             - uses: actions/download-artifact@v1
#               with:
#                   name: vhdl_ls
#                   path: vhdl_ls
            - uses: actions/setup-node@v1
              with:
                  node-version: '10'
            - run: npm install -g vsce
            - run: vsce publish -p $PUBLISH_TOKEN --packagePath vhdl_ls/vhdl-ls-${VERSION}.vsix
              env:
                PUBLISH_TOKEN: test
                VERSION: ${GITHUB_REF:11}
              
