name: Package extension

on: [push]

jobs:
    build_vhdl_ls_ubuntu:
        name: Build vhdl_ls - Ubuntu, musl
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Rust HDL
              uses: actions/checkout@v1
              with:
                  repository: kraigher/rust_hdl
            - name: Build vhdl_ls
              run: cargo build --release --package vhdl_parser --target x86_64-unknown-linux-musl
            - name: Upload vhdl_ls executable
              uses: actions/upload-artifact@v1
              with:
                  name: server/vhdl_ls
                  path: target/x86_64-unknown-linux-musl/release/vhdl_ls
    
    build_vhdl_ls_windows:
        name: Build vhdl_ls - Windows, MSVC
        runs-on: windows-latest
        steps:
            - name: Checkout Rust HDL
              uses: actions/checkout@v1
              with:
                  repository: kraigher/rust_hdl
            - name: Build vhdl_ls
              run: cargo build --release --package vhdl_parser
            - name: Upload vhdl_ls executable
              uses: actions/upload-artifact@v1
              with:
                  name: server/vhdl_ls.exe
                  path: target/release/vhdl_ls.exe
    
    package_extension:
        name: Package extension
        needs: [build_vhdl_ls_ubuntu, build_vhdl_ls_windows]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: '10' 
            - uses: actions/checkout@v1
            - run: npm install
            - run: npm package
