name: Package

on: [push]

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - run: npm install
      - run: npm install -g vsce
      - run: vsce package
      - run: mkdir vhdl-ls && cp *.vsix vhdl-ls
      - uses: actions/upload-artifact@v1
        with:
          name: vhdl-ls
          path: vhdl-ls

  publish:
    name: Publish
    if: startsWith(github.ref, 'refs/tags/v')
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: vhdl-ls
          path: vhdl-ls
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Print env
        run: |
          echo ${GITHUB_REF:11}
          ls
          ls vhdl-ls
      - run: npm install -g vsce
      - run: vsce publish -p $PUBLISH_TOKEN --packagePath vhdl-ls/vhdl-ls-${GITHUB_REF:11}.vsix
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
